name: Deploy to deploy-branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "milesbarrios13@gmail.com"
          git config --global user.name "milesbarrios"

      - name: Build and Deploy
        run: |
          git checkout -b deploy-branch
          # Your build commands (e.g., npm run build)
          git commit -am "Auto-deploy from master"
          git push origin deploy-branch
